## Python Numpy Basics

In [1]:
# importing numpy 
import numpy as np

#### Creating arrays in numpy

In [3]:
# Creating array from list
numpy_arr = np.array([1,2,3,4])

# Creating array from 2d list
numpy_arr_mat = np.array([[1,2,3],[4,5,6]])

print(numpy_arr)
print(numpy_arr_mat)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


#### Array Attributes

In [4]:
# Checking the shape of the array i.e the rows and columns an array contains
numpy_arr.shape

(4,)

In [5]:
numpy_arr_mat.shape

(2, 3)

In [6]:
# Checking the datatype of the np array
numpy_arr.dtype

dtype('int32')

#### Array creation routines

In [7]:
# Creating an array of zeros
numpy_arr_zeros = np.zeros((3,3)) # Creating an array of the shape 3,3
numpy_arr_zeros 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# Creating an array of all ones
numpy_arr_ones = np.ones((3,5)) #  Creating an array of the shape 3,5
numpy_arr_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# creating an identity matrix
numpy_arr_idmat = np.eye(3) # 3 is the shape of the identity matrix
numpy_arr_idmat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
# creating an array using arange function
numpy_arr_arange = np.arange(0,10,2)
numpy_arr_arange

array([0, 2, 4, 6, 8])

In [15]:
# creating an array using linspace
numpy_arr_linspace = np.linspace(0,1,5)
numpy_arr_linspace

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [5]:
# creating random array 
numpy_arr_rand = np.random.rand(3,3)*10
# the random values are between 0 and 1
numpy_arr_rand

array([[8.38037202, 1.07304952, 3.82481751],
       [7.80413561, 8.25044192, 9.5770665 ],
       [5.41716664, 7.89821921, 9.88750093]])

In [6]:
# generating random integer array with specified range
numpy_arr_randint = np.random.randint(0,10,(3,5))
numpy_arr_randint

array([[0, 6, 6, 8, 8],
       [6, 6, 7, 2, 3],
       [4, 5, 1, 1, 1]])

In [7]:
# generating random normal distributed array
numpy_arr_randn = np.random.randn(3,3)
numpy_arr_randn

array([[ 0.66150472, -0.74402686,  0.07521872],
       [-0.71941695, -0.40650025,  1.18387662],
       [ 2.06376776,  1.44815307, -0.77788642]])

####  Array Indexing and Slicing

In [7]:
arr = np.array([1,2,3,4])

arr[2]

3

In [3]:
arr[0:2]

array([1, 2])

In [4]:
# boolean indexing
arr[arr > 1]

array([2, 3, 4])

#### Statistical operations

In [5]:
print(arr.sum())
print(arr.mean())
print(arr.std())

10
2.5
1.118033988749895


In [8]:
# Dot product
dot_prod_ans = np.dot(arr,arr)
dot_prod_ans

30

#### Matrix operations

In [12]:
arr_1 = np.array([
    [1,2],
    [5,6]])
arr_2 = np.array([
    [11,22],
    [55,66]])

arr_1.shape

arr_2.shape


(2, 2)

In [14]:
# multiplication
# for multiplication the number of columns and rows in the first matrix should be equal to the number of rows and columns in the second matrix
matmul_ans = np.matmul(arr_1,arr_2)
matmul_ans

array([[121, 154],
       [385, 506]])

Reshaping the arrays

In [19]:
# while reshaping the array the number of elements in the array must remain the same
# as in arr_1 there are 4 elements so only possible reshaping that can be done is 1*4, 4*1, 2*2
arr_1.reshape(4,1)

array([[1],
       [2],
       [5],
       [6]])